version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8.9.4
    working_directory: /home/circleci/project

  node_modules_cache_params: &node_modules_cache_params
    key: node_modules-{{ .Branch }}-{{ checksum "./package-lock.json" }}
    paths:
      - node_modules

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Show system information.
          command: |
            echo "Node $(node -v)"
            echo "Npm $(npm -v)"
      - restore_cache:
          name: Restore Cache.
          <<: *node_modules_cache_params
      - run:
          name: Set up to gas clasp environment.
          command: npm install
      - save_cache:
          name: Saving Cache.
          <<: *node_modules_cache_params
      - run:
          name: Run Lint.
          command: npm run lint
      - run:
          name: Run Test.
          command: npm run test
  deploy:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Show system information.
          command: |
            echo "Node $(node -v)"
            echo "Npm $(npm -v)"
      - restore_cache:
          name: Restore Cache.
          <<: *node_modules_cache_params
      - run:
          name: Set up to gas clasp environment.
          command: npm install
      - save_cache:
          name: Saving Cache.
          <<: *node_modules_cache_params
      - run:
          name: Deploy to GAS.
          command: ./scripts/deploy-ci.sh
workflows:
  version: 2
  build_deploy_workflow:
    jobs:
      - build
      - deploy:
        requires:
          - build
          filters:
            branches:
              only: master

